name: Build and Push LLM Worker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push LLM Worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./llm-worker.Dockerfile
          push: true
          tags: your-dockerhub-username/legioxllmworker:latest # Make sure this matches your repo name
          # --- THE CRITICAL CHANGE ---
          # This 'build-args' line securely passes the HF_TOKEN secret from your
          # GitHub settings into the Docker build environment.
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 
